#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: Clone Clean Minutes Variable
    shell: 'cat /var/plexguide/cloneclean'
    register: cloneclean

  - cron:
      name: Hourly Clean PG Clone Clean
      special_time: "hourly"
      job: "bash /opt/pgclone/cloneclean.sh"
      state: present
    ignore_errors: yes
