#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  vars:
    service_vars:
      - { name: crypt.service }
      - { name: pgdrive.service }
      - { name: gdrive.service }
      - { name: gcrypt.service }
      - { name: tdrive.service }
      - { name: tcrypt.service }
      - { name: supertransfer2.service }
      - { name: unionfs.service }
      - { name: pgmove.service }
      - { name: move.service }
      - { name: pgblitz.service }
      - { name: plexdrive.service }
      - { name: st2monitor.service }
      - { name: pgunion.service }
  tasks:
    - name: Stop All Docker Containers
      shell: docker stop $(docker ps -a -q)

    - name: Get existing services
      stat:
        path: '/etc/systemd/system/{{ item.name }}'
      with_items: '{{ service_vars }}'
      register: check_service_name

    - name: Stop services
      systemd: state=stopped name={{ item.item.name }} daemon_reload=yes enabled=no
      with_items: '{{ check_service_name.results }}'
      when: item.stat.exists

    - name: 'Waiting for 2 seconds for services to stop'
      wait_for: timeout=2

    - name: Remove services
      file:
        path: '/etc/systemd/system/{{ item.item.name }}'
        state: absent
      with_items: '{{ check_service_name.results }}'
      when: item.stat.exists

    - shell: '[ -d "/mnt/gdrive" ] && du -s -B G /mnt/gdrive | cut -f1 | bc -l | rev | cut -c 2- | rev'
      register: gdrive_size
    - name: Ensuring gdrive path is empty when unmounted
      shell: 'rm -rf /mnt/gdrive/*'
      when: gdrive_size.stdout < 10

    - shell: '[ -d "/mnt/tdrive" ] && du -s -B G /mnt/tdrive | cut -f1 | bc -l | rev | cut -c 2- | rev'
      register: tdrive_size
    - name: Ensuring tdrive path is empty when unmounted
      shell: 'rm -rf /mnt/tdrive/*'
      when: tdrive_size.stdout < 10

    - shell: '[ -d "/mnt/gcrypt" ] && du -s -B G /mnt/gcrypt | cut -f1 | bc -l | rev | cut -c 2- | rev'
      register: gcrypt_size
    - name: Ensuring gcrypt path is empty when unmounted
      shell: 'rm -rf /mnt/gcrypt/*'
      when: gcrypt_size.stdout < 10

    - shell: '[ -d "/mnt/tcrypt" ] && du -s -B G /mnt/tcrypt | cut -f1 | bc -l | rev | cut -c 2- | rev'
      register: tcrypt_size
    - name: Ensuring tcrypt path is empty when unmounted
      shell: 'rm -rf /mnt/tcrypt/*'
      when: tcrypt_size.stdout < 10

    - shell: '[ -d "/mnt/unionfs" ] && du -s -B G /mnt/unionfs | cut -f1 | bc -l | rev | cut -c 2- | rev'
      register: pgunion_size
    - name: Ensuring pgunion path is empty when unmounted
      shell: 'rm -rf /mnt/unionfs/*'
      when: pgunion_size.stdout < 10
