#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  vars:
    service_vars:
      - { name: crypt.service }
      - { name: pgdrive.service }
      - { name: gdrive.service }
      - { name: gcrypt.service }
      - { name: tdrive.service }
      - { name: tcrypt.service }
      - { name: supertransfer2.service }
      - { name: unionfs.service }
      - { name: pgunion.service }
      - { name: pgmove.service }
      - { name: move.service }
      - { name: pgblitz.service }
      - { name: plexdrive.service }
      - { name: st2monitor.service }
  tasks:
    - name: Stop All Docker Containers
      shell: docker stop $(docker ps -a -q)

    - name: Get existing services
      stat:
        path: '/etc/systemd/system/{{ item.name }}'
      with_items: '{{ service_vars }}'
      register: check_service_name

    - name: Stop services
      systemd: state=stopped name={{ item.item.name }} daemon_reload=yes enabled=no
      with_items: '{{ check_service_name.results }}'
      when: item.stat.exists

    - name: 'Waiting for 2 seconds for services to stop'
      wait_for: timeout=2

    - name: Remove services
      file:
        path: '/etc/systemd/system/{{ item.item.name }}'
        state: absent
      with_items: '{{ check_service_name.results }}'
      when: item.stat.exists

    - name: Ensuring gdrive path is empty when unmounted
      shell: 'rm -rf /mnt/gdrive/*'

    - name: Ensuring tdrive path is empty when unmounted
      shell: 'rm -rf /mnt/tdrive/*'

    - name: Ensuring gcrypt path is empty when unmounted
      shell: 'rm -rf /mnt/gcrypt/*'

    - name: Ensuring tcrypt path is empty when unmounted
      shell: 'rm -rf /mnt/tcrypt/*'

    - name: Ensuring pgunion path is empty when unmounted
      shell: 'rm -rf /mnt/unionfs/*'
