#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
# NOTE: UnionFS does not mean 'unionfs', we keep using 'unionfs' for backward compat but have switched to mergerfs
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: include PGClone aliases
      include_tasks: '/pg/pgclone/alias.yml'

    - name: Transport Type
      shell: 'cat /pg/var/pgclone.transport'
      register: transport55

    - name: 'If Fact Matches - Encrypted Blitz'
      set_fact:
        path: 'remotes = gdrive: tdrive: gcrypt: tcrypt: {{hdpath}}/move'
      when: transport55.stdout == "eblitz"

    - name: 'If Fact Matches - Encrypted Move'
      set_fact:
        path: 'remotes = gdrive: gcrypt: {{hdpath}}/move'
      when: transport55.stdout == "emove"

    - name: 'If Fact Matches - UnEncrypted Blitz'
      set_fact:
        path: 'remotes = gdrive: tdrive: {{hdpath}}/move'
      when: transport55.stdout == "ublitz"

    - name: 'If Fact Matches - UnEncrypted Move'
      set_fact:
        path: 'remotes = gdrive: {{hdpath}}/move'
      when: transport55.stdout == "umove"

    - name: Creating Required Paths
      file: 'path={{hdpath}}/{{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true'
      with_items:
        - 'move'
        - 'downloads'
        - 'incomplete'
        - 'corn'

    - name: Creating Logs Path
      file: 'path=/pg/var/{{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true'
      with_items:
        - 'logs'

    - name: 'Setting ownership on logs'
      shell: 'chown -R 1000:1000 /pg/var/logs'

    - name: 'Setting ownership'
      shell: 'chown -R 1000:1000 {{hdpath}}/{{item}}'
      with_items:
        - 'move'
        - 'downloads'
        - 'incomplete'

    - name: 'Setting permissions'
      shell: 'chmod -R 775 {{hdpath}}/{{item}}'
      with_items:
        - 'move'
        - 'downloads'
        - 'incomplete'

    - name: Transport Type
      shell: 'echo "" >> /pg/var/rclone/blitz.conf'
    #      register: transport

    - name: Line Remover
      shell: 'sed -i -e "/\[(unionfs|pgunion)\]/,+2d" /pg/var/rclone/blitz.conf'

    - name: Transport Type
      shell: |
        echo "[pgunion]" >> /pg/var/rclone/blitz.conf
        echo "type = union" >> /pg/var/rclone/blitz.conf
        echo "{{path}}" >> /pg/var/rclone/blitz.conf
    #      register: transport

    - name: 'PG Blitz Execution'
      block:
        - name: Bandwidth Limit
          shell: 'cat /pg/var/blitz.bw'
          register: bandwidth

        - name: Install PG Blitz Script
          template:
            src: /pg/pgclone/scripts/pgblitz.sh
            dest: /pg/var/pgblitz.sh
            force: yes

        - name: Install PG Blitz Service
          template:
            src: /pg/pgclone/mounts/pgblitz.service
            dest: /etc/systemd/system/pgblitz.service
            force: yes

        - name: Reload PG Blitz Service
          systemd:
            daemon_reload: yes
            enabled: yes
            state: reloaded
            name: pgblitz

      when: (transport55.stdout == "eblitz") or
        (transport55.stdout == "ublitz")

    - name: 'PG Move Execution'
      block:
        - name: Bandwidth Limit
          shell: 'cat /pg/var/move.bw'
          register: bandwidth

        - name: Deploy Version
          shell: 'cat /pg/var/rclone/deploy.version'
          register: ver

        - name: Register HD Path
          shell: 'cat /pg/var/server.hd.path'
          register: hdpath

        - name: Install MOVE Script
          template:
            src: /pg/pgclone/scripts/pgmove.sh
            dest: /pg/var/pgmove.sh
            force: yes

        - name: Install MOVE Service
          template:
            src: /pg/pgclone/mounts/pgmove.service
            dest: /etc/systemd/system/pgmove.service
            force: yes

        - name: Reload MOVE Service
          systemd:
            daemon_reload: yes
            enabled: yes
            state: reloaded
            name: pgmove

      when: (transport55.stdout == "emove") or
        (transport55.stdout == "umove")

    - name: Install PGUnion Script
      template:
        src: /pg/pgclone/scripts/pgunion.sh
        dest: /pg/var/pgunion.sh
        force: yes

    - name: Install PGUnion Service
      template:
        src: /pg/pgclone/mounts/pgunion.service
        dest: /etc/systemd/system/pgunion.service
        force: yes

    - name: Reload PGUnion Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: pgunion

    - name: 'Waiting for PGUnion to initialize'
      wait_for:
        path: /pg/unity/plexguide
        timeout: 15
        delay: 2

    - name: Register HD Path
      shell: 'cat /pg/var/server.hd.path'
      register: hdpath

    - name: Restart All Docker Containers
      shell: docker restart $(docker ps -a -q)

    - cron:
        name: Hourly Clean PG Clone Clean
        special_time: "hourly"
        job: "bash /pg/pgclone/functions/cloneclean.sh"
        state: present
