#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Read Default Folder Choice
      shell: "cat /var/plexguide/pgclone.defaultFolders"
      register: defaultFolderChoice
      
    - name: Install TCrypt Service
      template:
        src: /opt/pgclone/templates/tcrypt.service
        dest: /etc/systemd/system/tcrypt.service
        force: yes

    - name: Reload TCrypt Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: tcrypt


    - name: Create TCrypt Folder
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /mnt/tcrypt
        
    - name: Create TCrypt Default Folders
      when: defaultFolderChoice.stdout.find('Yes') != -1
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /mnt/tcrypt/tv
        - /mnt/tcrypt/movies
        - /mnt/tcrypt/music
        - /mnt/tcrypt/ebooks
        - /mnt/tcrypt/abooks